### ISSUE TITLE
Sakai is not always stopping preventing a restart

### ISSUE THREAD

**Issue by jonespm** [sakaiproject/nightly-config#13]
An error in the restart that we've been noticing a lot lately is that Sakai doesn't always stop.

When it doesn't stop it prints out this message.

```
+ bin/stop.sh -force
Tomcat did not stop in time.
PID file was not removed.
To aid diagnostics a thread dump has been written to standard out.
```

It seems like it should proceed to say `"Killing Tomcat with the PID: $PID" `

I think this isn't working because the `stop.sh` scripts don't actually pass the args forward so the -force arg never gets through. 

Perhaps [changing these scripts](https://stackoverflow.com/a/3816747/3708872) to run `. $TOMCAT_CMD stop "$@"` will fix this.

**Comment by kenaragon** [comment]
Updated script.  Should fully stop moving forward.
